/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho01;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author lennon
 */
public class TelaEsteganografia extends javax.swing.JFrame {

    
    
    public TelaEsteganografia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescricao = new javax.swing.JLabel();
        painelImagem = new javax.swing.JScrollPane();
        lblImagem = new javax.swing.JLabel();
        btnAbrirImagem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextMensagem = new javax.swing.JTextArea();
        btnEteganografar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblImagem2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextInformacaoRecuperada = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextSenhaRecuperar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processamento de Imagens | Trabalho 01");
        setMinimumSize(new java.awt.Dimension(800, 550));
        setName("framePrincipal"); // NOI18N
        getContentPane().setLayout(null);

        lblDescricao.setFont(new java.awt.Font("Canaro Light DEMO", 0, 14)); // NOI18N
        lblDescricao.setText("Dados da imagem:");
        getContentPane().add(lblDescricao);
        lblDescricao.setBounds(20, 510, 760, 30);

        painelImagem.setViewportView(lblImagem);

        getContentPane().add(painelImagem);
        painelImagem.setBounds(10, 190, 360, 280);

        btnAbrirImagem.setFont(new java.awt.Font("Canaro Light DEMO", 0, 18)); // NOI18N
        btnAbrirImagem.setText("ABRIR IMAGEM");
        btnAbrirImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirImagemActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirImagem);
        btnAbrirImagem.setBounds(10, 10, 370, 40);

        jTextMensagem.setColumns(20);
        jTextMensagem.setRows(5);
        jScrollPane1.setViewportView(jTextMensagem);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 360, 60);

        btnEteganografar.setText("OK");
        btnEteganografar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEteganografarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEteganografar);
        btnEteganografar.setBounds(310, 153, 60, 30);

        jScrollPane2.setViewportView(lblImagem2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 190, 360, 280);

        jTextInformacaoRecuperada.setColumns(20);
        jTextInformacaoRecuperada.setRows(5);
        jTextInformacaoRecuperada.setEnabled(false);
        jScrollPane3.setViewportView(jTextInformacaoRecuperada);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(390, 60, 360, 80);

        jButton1.setText("Recuperar Informação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 150, 360, 30);

        jLabel1.setText("Imagem esteganografada");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 490, 360, 14);

        jLabel2.setText("Texto para ser esteganografado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 240, 14);

        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 154, 49, 20);

        jTextSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextSenha);
        jTextSenha.setBounds(60, 150, 240, 30);

        jLabel4.setText("Senha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 10, 30, 40);
        getContentPane().add(jTextSenhaRecuperar);
        jTextSenhaRecuperar.setBounds(430, 20, 320, 30);

        jLabel5.setText("Imagem original");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 490, 340, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* variaveis globais */
    BufferedImage imagemOriginal, imagemAuxiliar;
    private static final Random rand = new Random();
    
    String destino = "C:/Users/lennon/Documents/NetBeansProjects/ProcessamentoDeImagens/images/esteganografia.png";
    
    
    private void btnAbrirImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirImagemActionPerformed

      JFileChooser chooser = new JFileChooser(destino);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG ou PNG", "jpg", "png");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Abrir Imagem");
        int op = chooser.showOpenDialog(this);
        if(op == JFileChooser.APPROVE_OPTION){  
            File arq = chooser.getSelectedFile();  
            String path = arq.toString();  
            try {
                imagemOriginal = ImageIO.read(new File(path));
                imagemAuxiliar = imagemOriginal;
                //ImageIcon icon = new ImageIcon(imagemOriginal.getScaledInstance(painelImagem.getWidth(), painelImagem.getHeight(), java.awt.Image.SCALE_SMOOTH));
                ImageIcon icon = new ImageIcon(imagemOriginal);
                lblImagem.setIcon(icon);
                
                lblDescricao.setText("Dados da imagem:      Altura: " + imagemOriginal.getHeight() + 
                        " pixels      Largura: " + imagemOriginal.getWidth() + " pixels.");
                
                System.out.println("Arquivo " + arq.getName() + " aberto com sucesso.");
	    }
	    catch(IOException e){
		System.out.println("Erro IO Exception! Verifique se o arquivo especificado existe e tente novamente.");
	    }
	    catch(Exception e){
		System.out.println("Erro Exception! " + e.getMessage());
	    }                   
        }
        
    }//GEN-LAST:event_btnAbrirImagemActionPerformed

    private void btnEteganografarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEteganografarActionPerformed
        
        String mensagem = jTextMensagem.getText();
        String password = jTextSenha.getText();
   
        Esteganografia este = new Esteganografia(); 
        
        if (!validarDados(mensagem, password)){
            JOptionPane.showMessageDialog(null, "Os dois campos são obrigatórios");
            return;
        }
        Criptografia c= new Criptografia();
        String mensagemCriptografada = c.CriptografarMensagem(mensagem, password);
        este.InserirMensagem(this.imagemOriginal, this.destino, mensagemCriptografada);
        
        ImageIcon icon = new ImageIcon(imagemOriginal);
        lblImagem2.setIcon(icon);
        
        
    }//GEN-LAST:event_btnEteganografarActionPerformed
    public boolean validarDados(String mensagem, String password){
        if (mensagem.equals("") || password.equals("")){
            return false;
        }
        return true;
    }
    private void jTextSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Esteganografia este = new Esteganografia(); 
        String respCriptografada= este.lerMensagem(destino);
        String password = jTextSenhaRecuperar.getText();
        if (password.equals("") || password.length() < 2){
            JOptionPane.showMessageDialog(null, "A senha é obrigatório");
            return;
        }
                
        /*Descriptografa a resposta*/
        Criptografia criptografia= new Criptografia();
        String mensagemExtraida= criptografia.DescriptografarMensagem(respCriptografada, password);
        if (mensagemExtraida == null){
           JOptionPane.showMessageDialog(null, "Senha incorreta");
           return;
        }
        jTextInformacaoRecuperada.setText(mensagemExtraida);
    }//GEN-LAST:event_jButton1ActionPerformed
    
  
            
           
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception  ex) {
            java.util.logging.Logger.getLogger(TelaEsteganografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); /* Windows */
                    //UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel"); /* Linux */
                } catch (Exception  ex) {
                    Logger.getLogger(TelaEsteganografia.class.getName()).log(Level.SEVERE, null, ex);
                }
                new TelaEsteganografia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirImagem;
    private javax.swing.JButton btnEteganografar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextInformacaoRecuperada;
    private javax.swing.JTextArea jTextMensagem;
    private javax.swing.JTextField jTextSenha;
    private javax.swing.JTextField jTextSenhaRecuperar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblImagem2;
    private javax.swing.JScrollPane painelImagem;
    // End of variables declaration//GEN-END:variables
}
